[workspace]
resolver = "2"
members = [
    "crates/protocol",
    "apps/server",
    "apps/agent",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/theadeyemiolayinka/hookrelay"
rust-version = "1.80"
authors = ["TheAdeyemiOlayinka <github.com/theadeyemiolayinka>"]

[workspace.dependencies]
# Async runtime
tokio = { version = "1.40", features = ["full"] }
tokio-tungstenite = { version = "0.24", features = ["rustls-tls-native-roots"] }

# Web framework
axum = { version = "0.7", features = ["ws", "macros"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["trace", "cors", "limit", "fs", "set-header", "compression-gzip"] }

# Database
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio-rustls", "sqlite", "macros", "migrate", "chrono", "uuid"] }

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Error handling
thiserror = "1"
anyhow = "1"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# Time
chrono = { version = "0.4", default-features = false, features = ["serde", "clock"] }

# IDs
uuid = { version = "1", features = ["v4", "serde"] }

# HTTP client (agent)
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "stream"] }

# CLI
clap = { version = "4", features = ["derive", "env"] }

# Crypto / hashing
argon2 = "0.5"
rand = "0.8"
subtle = "2"

# Misc
hex = "0.4"
base64 = "0.22"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true
